## Programming for Data Science 
### Project Notebook: "Where should I live?" 
#### Group Members:
- Afonso Fernandes / 20241710
- Lourenço Lima / 20241711
- Pedro Jorge / 20241819
- David Morais / 20241759
## Project Repository
GitHub Repository:  
https://github.com/afonsolince06/-Where-should-I-live-PDS-Project

### **Introduction**

In this part of the project, the goal is to build an interactive map of Europe that allows users to explore key information about major European cities. The task combines web scraping, data integration, and geospatial visualization to create an informative and interactive tool.

To accomplish this, we will:

-Scrape the geographical coordinates of each city directly from the Wikipedia Main Page, ensuring accuracy and consistency with the provided dataset.

-Match the scraped coordinates with the dataset entries so that each city is correctly assigned to its corresponding country, population, average salary, and cost of living.

-Use the cleaned and enriched dataset to construct an interactive map of Europe, where each city can be clicked or hovered over to display its relevant information.

By the end of this section, we will have a fully functional map that visually represents European cities and provides meaningful insights through an intuitive interface. This builds on the skills developed earlier in the project and introduces new concepts in geospatial data handling and visualization.

### **Importing the necessary libraries for webscraping and map building.**

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
import re
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

### **Importing the already cleaned dataset**

In [25]:
city_data = pd.read_csv('city_data_cleaned.csv') # Load the cleaned city data
city_data_coords = city_data.copy() # Create a copy to add coordinates
# Fill the coordinate columns with NaN values
city_data_coords['Latitude'] = np.nan
city_data_coords['Longitude'] = np.nan

### **5. Web Scrapping**
In this section, Selenium is used to automatically retrieve the geographic coordinates (latitude and longitude) of European cities from the cleaned dataset `city_data_coords` using information available on Wikipedia. The process begins with the implementation of the function `get_city_coordinates`, which opens a web browser and navigates to the Wikipedia main page. For each city in the dataset, a search is performed—optionally including the country name to improve accuracy—followed by navigation to the corresponding city article, where the geographic coordinates are extracted.

The retrieved coordinates are subsequently stored in the dataset through the function `fill_dataset_coords`.

In [26]:
wikipedia_url = "https://en.wikipedia.org/wiki/Main_Page" # Wikipedia main page URL


def get_city_coordinates(city_name):
    """
    Starts on the Wikipedia main page and searches for the given city name.

    Parameters:
    city_name (str): The name of the city to search for.

    Returns:
    The city page URL.
    """

    if city_name == 'Rotterdam': # Special case for Rotterdam
        try:
            # Navigate to Wikipedia main page
            driver.get(wikipedia_url)

            # Find the search input box and enter the city name
            search_input = WebDriverWait(driver, 15).until(EC.element_to_be_clickable((By.ID, "searchInput")))
            search_input.send_keys(city_name)
            search_input.send_keys(Keys.RETURN)

        
            WebDriverWait(driver, 15).until(EC.presence_of_element_located((By.ID, "firstHeading"))) # Wait for page to load
            lat = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, "//span[@class='latitude']")))
            latitude = driver.execute_script("return arguments[0].textContent;", lat)
            long = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.XPATH, "//span[@class='longitude']")))
            longitude = driver.execute_script("return arguments[0].textContent;", long)
            return (latitude.strip(), longitude.strip())
        
        finally:
            driver.quit() # Close the browser

    else: # General case for other cities
        # Set up the Selenium WebDriver 
        options = webdriver.ChromeOptions()
        driver = webdriver.Chrome(options=options)
        driver.maximize_window()
        
        try:
            # Navigate to Wikipedia main page
            driver.get(wikipedia_url)
            # Find the search input box and enter the city name
            search_input = WebDriverWait(driver, 15).until(EC.element_to_be_clickable((By.ID, "searchInput")))
            search_input.send_keys(city_name)
            search_input.send_keys(Keys.RETURN)
          
            WebDriverWait(driver, 15).until(EC.presence_of_element_located((By.ID, "firstHeading"))) # Wait for page to load
            city_latitude = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.CLASS_NAME, "latitude")))
            city_longitude = WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.CLASS_NAME, "longitude")))
            return (city_latitude.text, city_longitude.text)
            
        finally:
            driver.quit() # Close the browser
    


def fill_dataset_coords(df):
    """
    Fills the dataset with latitude and longitude coordinates for each city.
    Parameters:
    df (DataFrame): The DataFrame containing city data.
    Returns:
    The updated DataFrame with latitude and longitude columns filled.
    """

    for city in df['City']:
        try: # Attempt to get coordinates using "City, Country" format first
            df.loc[df['City'] == city, ['Latitude', 'Longitude']] = get_city_coordinates(f"{city}, {df.loc[city_data_coords['City'] == city, 'Country'].values[0]}")
        except Exception: # If that fails, try just the city name
            df.loc[df['City'] == city, ['Latitude', 'Longitude']] = get_city_coordinates(city)
    return df





# Filling the dataset with coordinates
fill_dataset_coords(city_data_coords)


display(city_data_coords.tail(40)) # Checking the last 40 rows to check if the function worked for Rotterdam as it was the only city we had issues with
city_data_coords.loc[city_data_coords['City'] == 'Rotterdam', ['Latitude', 'Longitude']] = ('51°55′N', '4°29′E') # As we were not able to scrapte the coordinates for Rotterdam, we will fill it manually just so we have it in the map
display(city_data_coords.loc[city_data_coords['City'] == 'Rotterdam', ['City','Latitude', 'Longitude']]) # Checking if Rotterdam coordinates were filled correctly

C:\Users\ASUS\AppData\Local\Temp\ipykernel_19136\4113309029.py:71: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '47°48′00″N' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.

C:\Users\ASUS\AppData\Local\Temp\ipykernel_19136\4113309029.py:71: FutureWarning:

Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '13°02′42″E' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.

,Country,City,Population Density,Population,Working Age Population,Youth Dependency Ratio,Unemployment Rate,GDP per Capita,Days of very strong heat stress,Main Spoken Languages,Average Monthly Salary,Average Rent Price,Average Cost of Living,Last Data Update,Individual Languages,Spendable Income,Latitude,Longitude
44,Italy,Venice,852.0,557748,347781.0,19.3,6.1,39681.0,6,Italian,1400,1150,1500,2023-03-23,['Italian'],-100,45°26′15″N,12°20′9″E
45,Latvia,Riga,152.0,930245,594604.0,25.6,5.3,39537.0,0,"Latvian, Russian",1300,600,1250,2023-12-07,"['Latvian', 'Russian']",50,56°56′56″N,24°6′23″E
46,Luxembourg,Luxembourg,236.0,610825,424824.0,23.1,5.6,112143.0,2,"Luxembourgish, French, German, English",4200,2100,3300,2024-11-29,"['Luxembourgish', 'French', 'German', 'English']",900,49°36′42″N,6°7′55″E
47,Malta,Malta,1845.0,456490,309610.0,20.2,3.7,44781.0,0,"Maltese, English",1450,1000,1400,2024-02-28,"['Maltese', 'English']",50,35°54′N,14°31′E
48,Netherlands,Amsterdam,864.0,2862590,1913803.0,24.0,3.3,73065.0,2,"Dutch, English",3750,1150,2550,2024-07-21,"['Dutch', 'English']",1200,52°22′22″N,04°53′37″E
49,Netherlands,Eindhoven,551.0,760059,495081.0,23.2,3.3,62660.0,3,"Dutch, English",3100,1100,1900,2023-06-20,"['Dutch', 'English']",1200,51°26′N,5°29′E
50,Netherlands,Rotterdam,864.0,1860582,1213524.0,25.2,4.1,54780.0,2,"Dutch, English",3100,1350,2100,2023-10-11,"['Dutch', 'English']",1000,,
51,Netherlands,The Hague,2646.0,1103137,733794.0,25.1,4.2,54976.0,1,"Dutch, English",3500,1250,2000,2023-09-17,"['Dutch', 'English']",1500,52°04′48″N,04°18′36″E
52,Netherlands,Utrecht,924.0,898712,592246.0,26.2,3.0,67062.0,3,"Dutch, English",3200,1300,2000,2024-05-26,"['Dutch', 'English']",1200,52°05′27″N,05°07′18″E
53,Norway,Bergen,126.0,419854,278139.0,27.2,4.6,51095.0,0,"Norwegian, English",3500,1200,2100,2023-04-30,"['Norwegian', 'English']",1400,60°23′22″N,5°19′48″E
54,Norway,Oslo,189.0,1398715,947183.0,26.4,5.4,67128.0,0,"Norwegian, English",3600,1350,2200,2024-12-12,"['Norwegian', 'English']",1400,59°54′48″N,10°44′20″E
55,Norway,Stavanger,122.0,339690,225096.0,30.4,1.6,58137.0,0,"Norwegian, English",3500,1100,2000,2024-03-15,"['Norwegian', 'English']",1500,58°58′12″N,05°43′53″E
56,Poland,Cracow,376.0,1410424,938323.0,23.7,2.9,40721.0,0,"Polish, English",1400,1000,1500,2023-07-11,"['Polish', 'English']",-100,50°03′41″N,19°56′14″E
57,Poland,Lodz,536.0,907836,587774.0,20.4,3.7,37618.0,2,Polish,1200,800,1200,2024-08-05,['Polish'],0,51°46′37″N,19°27′17″E
58,Poland,Warsaw,370.0,3181548,2068260.0,25.7,2.2,67994.0,1,"Polish, English",1500,950,1450,2023-11-13,"['Polish', 'English']",50,52°13′48″N,21°00′40″E
59,Portugal,Braga,501.0,247719,169611.0,20.3,7.0,28783.0,1,Portuguese,1000,700,1100,2024-01-31,['Portuguese'],-100,41°33′4″N,8°25′42″W
60,Portugal,Coimbra,162.0,264656,166311.0,19.5,5.3,30407.0,2,Portuguese,1000,650,1050,2024-06-19,['Portuguese'],-50,40°12′10″N,8°24′50″W
61,Portugal,Lisbon,695.0,3008000,1871604.0,25.4,7.4,42363.0,1,"Portuguese, English",1220,1050,1600,2024-10-04,"['Portuguese', 'English']",-380,38°43′31″N,09°09′00″W
62,Portugal,Porto,1343.0,1280190,840851.0,20.5,7.0,31339.0,0,Portuguese,1100,900,1400,2023-05-23,['Portuguese'],-300,41°9′0″N,8°36′39″W
63,Romania,Giroc,1500.0,351851,244969.0,21.2,3.4,34708.0,7,Romanian,900,450,900,2023-08-18,['Romanian'],0,45°42′N,21°14′E
64,Slovak Republic,Bratislava,1201.0,440611,291146.0,26.0,2.4,77457.0,3,"Slovak, English",1200,850,1250,2024-04-25,"['Slovak', 'English']",-50,48°08′38″N,17°06′35″E
65,Slovenia,Ljubljana,1065.0,292988,193867.0,21.9,4.5,51726.0,0,"Slovene, English",1600,800,1550,2023-10-20,"['Slovene', 'English']",50,46°03′05″N,14°30′22″E
66,Spain,Barcelona,1918.0,5034925,3331345.0,22.6,11.0,45016.0,0,"Spanish, Catalan",2094,1450,1630,2024-10-18,"['Spanish', 'Catalan']",464,41°23′N,2°11′E
67,Spain,Madrid,873.0,6882461,4617753.0,23.0,10.8,51020.0,18,Spanish,2271,1100,1589,2023-05-14,['Spanish'],682,40°30′N,3°40′W
68,Spain,Malaga,571.0,869096,585608.0,23.5,17.7,27694.0,0,"Spanish, English",2200,1312,1400,2023-11-27,"['Spanish', 'English']",800,36°43′10″N,4°25′12″W
69,Spain,Seville,330.0,1549641,1037225.0,25.0,21.6,30004.0,53,Spanish,2300,650,1150,2024-09-01,['Spanish'],1150,37°23′24″N,5°59′24″W
70,Spain,Valencia,722.0,1748142,1162828.0,22.6,13.7,33570.0,5,"Spanish,Valencian",2400,1190,1300,2023-06-04,"['Spanish', 'Valencian']",1100,39°28′12″N,00°22′35″W
71,Sweden,Gothenburg,245.0,1037675,672152.0,28.2,6.3,49588.0,0,"Swedish, English",2500,1200,2100,2023-03-10,"['Swedish', 'English']",400,57°42′27″N,11°58′03″E
72,Sweden,Malmo,368.0,680335,436271.0,29.4,9.2,44387.0,0,"Swedish, English",2400,1100,2000,2024-07-07,"['Swedish', 'English']",400,55°36′21″N,13°02′09″E
73,Sweden,Stockholm,334.0,2344124,1534225.0,28.5,6.2,70950.0,0,"Swedish, English",2700,1400,2300,2024-09-11,"['Swedish', 'English']",400,59°19′46″N,18°4′7″E
74,Switzerland,Basel,793.0,550152,358020.0,21.5,5.3,94826.0,5,"German, English, French",6366,2500,4239,2023-01-19,"['German', 'English', 'French']",2127,47°33′17″N,07°35′26″E
75,Switzerland,Geneva,1112.0,597269,404313.0,23.8,9.9,83747.0,1,"French, English",5794,2818,4263,2024-09-28,"['French', 'English']",1531,46°12′06″N,06°08′49″E
76,Switzerland,Zurich,1058.0,1384728,939270.0,22.3,4.7,80431.0,4,"German, English",6636,3190,4862,2023-05-06,"['German', 'English']",1774,47°22′28″N,08°32′28″E
77,Turkiye,Adana,552.0,1074543,718256.0,37.8,12.2,19945.0,59,Turkish,750,350,800,2024-05-02,['Turkish'],-50,37°0′N,35°19.28′E
78,Turkiye,Ankara,1922.0,4843511,3417691.0,30.0,14.4,38916.0,3,Turkish,900,450,900,2023-06-08,['Turkish'],0,39°55′44″N,32°51′17″E
79,United Kingdom,Edinburgh,527.0,907580,614959.0,23.4,3.7,54002.0,0,"English, Scots Gaelic",2500,1010,2050,2023-08-15,"['English', 'Scots Gaelic']",450,55°57′12″N,3°11′21″W
80,United Kingdom,Glasgow,548.0,1845020,1229657.0,24.2,4.8,39666.0,0,"English, Scots",2300,1050,1950,2023-05-28,"['English', 'Scots']",350,55°51′40″N,04°15′00″W
81,United Kingdom,Leeds,517.0,2641062,1677791.0,30.0,3.5,37990.0,0,"English, Urdu",2300,1000,2000,2024-11-03,"['English', 'Urdu']",300,53°47′51″N,01°32′37″W
82,United Kingdom,Liverpool,1560.0,1544216,983056.0,26.8,7.5,33749.0,0,English,2250,950,1800,2024-01-23,['English'],450,53°24′26″N,2°59′30″W
83,United Kingdom,London,1777.0,12396541,8274794.0,29.1,6.1,69863.0,0,"English, Urdu, Bengali, Polish",2750,1900,2800,2023-04-09,"['English', 'Urdu', 'Bengali', 'Polish']",-50,51°30′26″N,0°7′39″W

         City Latitude Longitude
50  Rotterdam  51°55′N    4°29′E

### **Exporting the final DataFrame with the scraped coordinates (in DMS format)**

In [27]:
city_data_coords.to_csv('city_data_with_coords.csv', index=False) # Saving the dataset with coordinates to a CSV file

# Safety net in case we need to reload the DataFrame with coordinates after deleting them by accident
city_data_coords = pd.read_csv('city_data_with_coords.csv')

### **6. Interactive Map**

This section is where we build the interactive map with all the cities in the provided dataset and the hover information that was asked for in the guidelines.

Since the coordinates obtained from Wikipedia are provided in DMS (Degrees, Minutes, Seconds) format, an additional function, `dms_to_decimal`, is applied to convert them into decimal degrees. These processed coordinates are then used as input for the construction of an interactive map, allowing for a clear geographical representation of the analyzed cities.

In [ ]:
# Iterative Map Building and Visualization

def dms_to_decimal(dms_coords):
    """
    Converts the coordinates from the DMS (Degrees, Minutes, Seconds) format that they were scraped in to a decimal format to be used in the map visualization.
    
    Parameters:
    dms_coords (str): The coordinates in DMS format.
    
    Returns:
    The coordinates in decimal format.
    """
    dms_parts = re.split('[°′″NEW]', dms_coords) # Split the DMS string into its components and taking care of N, E, W, S characters
    degrees = float(dms_parts[0]) # Degrees part is always present and it's the first element
    minutes = float(dms_parts[1]) if len(dms_parts) > 1 and dms_parts[1] else 0 # Minutes part may be missing, it's the second element
    seconds = float(dms_parts[2]) if len(dms_parts) > 2 and dms_parts[2] else 0 # Seconds part may be missing, it's the third element

    decimal_coords = degrees + (minutes / 60) + (seconds / 3600) # Formula to convert DMS to decimal

    if 'S' in dms_coords or 'W' in dms_coords:
        decimal_coords = -decimal_coords # Southern and western hemispheres are negative

    return decimal_coords

city_data_coords['Latitude'] = city_data_coords['Latitude'].apply(dms_to_decimal)
city_data_coords['Longitude'] = city_data_coords['Longitude'].apply(dms_to_decimal)

# Drop rows with missing coordinates so the map visualization works properly
map_df = city_data_coords.dropna(subset=['Latitude', 'Longitude'])

# Create the scatter map
fig_map = px.scatter_map(
        map_df,
        lat="Latitude",
        lon="Longitude",
        hover_name="City",
        hover_data={
            "Latitude": False, "Longitude": False,
            "Country": True,
            "Population": ':,.0f', 
            "Average Monthly Salary": ':,.0f €', 
            "Average Cost of Living": ':,.0f €'  
        },
        color="Average Monthly Salary", 
        size="Population", 
        size_max=25,             
        color_continuous_scale="Turbo",
        zoom=3, 
        height=700,
        title="Iterative Map of Cities with Population, Average Monthly Salary, and Cost of Living"
    )

# Update layout for better visualization
fig_map.update_layout(mapbox_style="open-street-map")
fig_map.update_layout(margin={"r":0,"t":40,"l":0,"b":0})
fig_map.show()